"""
Smart Orchestrator V2 Demo

Demonstrates the V2 guide-based orchestration flow.
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from ci_architecture.orchestrator import (
    SmartOrchestratorV2,
    Zone,
    OrchestratorGuide
)


def demo_v2_basic():
    """Demo V2 basic flow without actual L0/L1/L2 routers"""
    print("=" * 60)
    print("Smart Orchestrator V2 - Basic Demo")
    print("=" * 60)
    
    # Create V2 orchestrator (without actual routers for demo)
    orchestrator = SmartOrchestratorV2()
    
    # Demo 1: Zone D → Zone C (Clarify)
    print("\n[Demo 1] Zone D → Zone C (Information Completion)")
    print("-" * 50)
    
    # Simulate a query that would be Zone D
    print("Query: 'How to use this medicine?'")
    print("Expected: Zone D (C=0, I=0) → needs orchestrator_guide")
    
    # Since we don't have actual L0/L1/L2 routers, let's demonstrate the data structures
    guide = OrchestratorGuide.from_dict({
        'missing_info': ['Medicine name', 'Patient age', 'Symptoms'],
        'decomposable': False,
        'recommended': ['clarify'],
        'sub_problem_hints': [],
        'confidence': 0.85,
        'validates_classification': True
    })
    
    print(f"\nGenerated Guide:")
    print(f"  Missing info: {guide.missing_info}")
    print(f"  Decomposable: {guide.decomposable}")
    print(f"  Recommended strategies: {guide.recommended}")
    print(f"  Confidence: {guide.confidence}")
    
    # Demo 2: Zone B → Zone A/C (Multi-strategy)
    print("\n[Demo 2] Zone B → Zone A/C (Multi-strategy)")
    print("-" * 50)
    
    print("Query: 'How to design a high-concurrency e-commerce system?'")
    print("Expected: Zone B (C=1, I=0) → can clarify OR decompose")
    
    guide_multi = OrchestratorGuide.from_dict({
        'missing_info': ['QPS requirements', 'Budget constraints'],
        'decomposable': True,
        'recommended': ['clarify', 'decompose'],  # Both options!
        'sub_problem_hints': [
            'Architecture patterns for high concurrency',
            'Database design for e-commerce',
            'Caching strategies',
            'Load balancing approaches'
        ],
        'confidence': 0.82,
        'validates_classification': True
    })
    
    print(f"\nGenerated Guide:")
    print(f"  Missing info: {guide_multi.missing_info}")
    print(f"  Decomposable: {guide_multi.decomposable}")
    print(f"  Recommended strategies: {guide_multi.recommended}")
    print(f"  Sub-problem hints: {len(guide_multi.sub_problem_hints)} items")
    
    print("\n  Strategy options:")
    print("    1. Clarify: Ask for QPS and budget → Zone A")
    print("    2. Decompose: Split into 4 sub-problems → Zone C → Aggregate to A")
    print("    3. User can choose, or orchestrator tries clarify first")
    
    # Demo 3: Multi-strategy plan
    print("\n[Demo 3] Multi-strategy Plan Execution")
    print("-" * 50)
    
    from ci_architecture.orchestrator.smart_orchestrator_v2 import (
        CIState, ZoneTransitionEngineV2
    )
    
    ci = CIState(C=0.9, I=0.2, sigma_c=0.85, sigma_i=0.8, 
                 query="How to design a high-concurrency e-commerce system?")
    
    engine = ZoneTransitionEngineV2()
    plan = engine.plan_from_guide(ci, guide_multi)
    
    print(f"Original Zone: {plan.original_zone.value}")
    print(f"Target Zone: {plan.target_zone.value}")
    print(f"Primary Strategy: {plan.primary_strategy}")
    print(f"All Strategies: {plan.strategies}")
    print(f"User Selectable: {plan.user_selectable}")
    print(f"Missing Info: {plan.missing_info_list}")
    
    if plan.sub_problems:
        print(f"\nSub-problems (if decomposition chosen):")
        for sp in plan.sub_problems:
            print(f"  - [{sp.id}] {sp.query}")
    
    print("\n" + "=" * 60)
    print("V2 Key Improvements:")
    print("  1. Zone B/D must have orchestrator_guide")
    print("  2. Guide generated by Level 2 (professional judgment)")
    print("  3. Supports multiple strategies [clarify, decompose]")
    print("  4. Max 2 transition rounds to prevent loops")
    print("  5. Orchestrator executes, doesn't decide")
    print("=" * 60)


def demo_v2_session():
    """Demo V2 session management with multi-turn"""
    print("\n" + "=" * 60)
    print("Smart Orchestrator V2 - Session Demo")
    print("=" * 60)
    
    orchestrator = SmartOrchestratorV2()
    session_id = "demo_session_001"
    
    print(f"\nSession: {session_id}")
    print("Scenario: User asks about medicine usage")
    
    # Round 1: Initial query (Zone D)
    print("\n[Round 1] Initial Query")
    print("  User: 'How to use this medicine?'")
    print("  System: Detected Zone D, needs clarification")
    print("  Missing: ['Medicine name', 'Patient age', 'Symptoms']")
    print("  Action: Ask user for clarification")
    
    # Round 2: User provides partial info
    print("\n[Round 2] User Provides Partial Info")
    print("  User: Medicine is Amoxicillin")
    
    result = orchestrator.continue_with_info(session_id, {
        'medicine': 'Amoxicillin'
    })
    
    print(f"  Status: {result.get('status')}")
    if result.get('status') == 'transition_required':
        print("  Still Zone D, need more info")
        print(f"  Missing: {result.get('clarification', {}).get('missing_info', [])}")
    
    # Round 3: User provides more info
    print("\n[Round 3] User Provides More Info")
    print("  User: Medicine is Amoxicillin, patient is 35 years old, for cold")
    
    # Simulate reaching Zone C
    print("  System: Now have enough info")
    print("  Zone: D → C")
    print("  Action: Direct output of usage instructions")
    
    print("\n" + "=" * 60)
    print(f"Total transition rounds: 2 (within limit)")
    print("=" * 60)


if __name__ == "__main__":
    demo_v2_basic()
    demo_v2_session()
